services:
  postgres:
    image: postgres:15
    container_name: postgres_db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: timmipay
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  redis:
    image: "redis:latest"
    container_name: redis_db
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --requirepass supersecret
    environment:
      REDIS_PASSWORD: supersecret


  # Тестовая база данных
  postgres_test:
    image: postgres:15
    container_name: postgres_test_db
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: timmipay_test
    volumes:
      - pgdata_test:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  redis_test:
    image: "redis:latest"
    container_name: redis_test_db
    restart: always
    ports:
      - "6380:6379"

volumes:
  pgdata:
  pgdata_test:


  #app:
    #build:
      #context: .
      #dockerfile: Dockerfile
    #container_name: cxx_app
    #restart: always
    #depends_on:
      #- postgres
    #environment:
      #- DB_TYPE=postgres
    #ports:
      #- "8080:8080"
    #volumes:
      #- ./config.json:/app/config.json